/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FoodRouteImport } from './routes/food'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as HealthRouteImport } from './routes/health'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/food': typeof FoodRoute
  '/grocery': typeof GroceryRoute
  '/health': typeof HealthRoute
  '/notes': typeof NotesRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/food': typeof FoodRoute
  '/grocery': typeof GroceryRoute
  '/health': typeof HealthRoute
  '/notes': typeof NotesRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/food': typeof FoodRoute
  '/grocery': typeof GroceryRoute
  '/health': typeof HealthRoute
  '/notes': typeof NotesRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/finance'
    | '/food'
    | '/grocery'
    | '/health'
    | '/notes'
    | '/reminders'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/finance'
    | '/food'
    | '/grocery'
    | '/health'
    | '/notes'
    | '/reminders'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/finance'
    | '/food'
    | '/grocery'
    | '/health'
    | '/notes'
    | '/reminders'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FinanceRoute: typeof FinanceRoute
  FoodRoute: typeof FoodRoute
  GroceryRoute: typeof GroceryRoute
  HealthRoute: typeof HealthRoute
  NotesRoute: typeof NotesRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FinanceRoute: FinanceRoute,
  FoodRoute: FoodRoute,
  GroceryRoute: GroceryRoute,
  HealthRoute: HealthRoute,
  NotesRoute: NotesRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
